strategy:
  matrix:
    windows-stable:
      imageName: 'windows-2019'
      rustup_toolchain: nightly-2020-01-07
    mac-stable:
      imageName: 'macos-10.14'
      rustup_toolchain: nightly-2020-01-07
    linux-stable:
      imageName: 'ubuntu-18.04'
      rustup_toolchain: nightly-2020-01-07

pool:
  vmImage: $(imageName)

steps:
  - script: cargo build --manifest-path packages/catalyst-ffi/Cargo.toml --verbose
    displayName: Cargo build 
  - script: cargo test --manifest-path packages/catalyst-ffi/Cargo.toml --verbose
    displayName: Cargo test 
  - task: CopyFiles@2
    displayName: copy windows runtime
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/packages/catalyst-ffi/target/debug'
      TargetFolder: '$./runtimes/win-x64/native'
      Contents: 'catalyst_ffi.*'
  - task: CopyFiles@2
    displayName: copy macos runtime
    condition: eq( variables['Agent.OS'], 'Darwin' )
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/packages/catalyst-ffi/target/debug'
      TargetFolder: '$./runtimes/osx-x64/native'
      Contents: 'libcatalyst_ffi.*'
  - task: CopyFiles@2
    displayName: copy linux runtime
    condition: eq( variables['Agent.OS'], 'Linux' )
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/packages/catalyst-ffi/target/debug'
      TargetFolder: '$./runtimes/linux-x64/native'
      Contents: 'libcatalyst_ffi.*'
  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      projects: '*.csproj'
      arguments: '--configuration=$(BuildConfiguration)'
      failOnStandardError: 'true'
    timeoutInMinutes: 10
  - task: DotNetCoreCLI@2
    displayName: pack project
    inputs: 
      command: 'pack'
      nobuild: false
      includesymbols: false
      includesource: false
      verbosityPack: 'Diagnostic'
      failOnStandardError: 'true'
      buildProperties: 'VersionSuffix=$(Build.BuildId)$(release.type)'
    timeoutInMinutes: 10
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      ArtifactName: 'catalystffi-nugets'