[package]
name = "catalyst-ffi"
version = "0.1.0"
authors = ["Fran <fran.sl@atlascity.io> (https://atlascity.io)"]
edition = "2018"
description = "A rust ffi component providing functionality from dalek-cryptography along with some custom cryptographic functions"
repository = "https://github.com/catalyst-network/catalyst-rs/packages/catalyst-ffi"
homepage = "https://github.com/catalyst-network/catalyst-rs/packages/catalyst-ffi"
readme = "README.md"
license = "MIT"
keywords = ["rust", "cryptography", "crypto", "catalyst", "dalek-cryptography"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
catalyst-common = { path = "../catalyst-common"}
libc = "0.2.66"
rand = "0.7"

[profile.dev]
opt-level = 3

[dev-dependencies]
criterion = "0.3"
hex = "0.4.1"
protobuf = "2.10.0"

[[bench]]
name = "benchmarks"
harness = false

[lib]
name = "catalyst_ffi"
path = "src/lib.rs"
crate-type = ["cdylib"]
